file structure
GSG-G10/divano pull request #2
Opened 2021-10-01 18:28 UTC by modrayyes

Front-end file structure (npx create-react-app)

2021-10-01 18:51 UTC, NadiaJalalTamimi submitted a review, later dismissed

2021-10-01 18:51 UTC, ahmadfarid-059 submitted a review, later dismissed

2021-10-01 21:54 UTC, Mu7ammadAbed commented
You need to create 2 folders, one for your server and another one for client which should include the react files

2021-10-01 21:58 UTC, Mu7ammadAbed requested changes
You should install eslint and set its configurations

2021-10-01 21:58 UTC, Mu7ammadAbed commented on public/index.html
> +      content="Web site created using create-react-app"
You should edit this

2021-10-01 21:58 UTC, Mu7ammadAbed commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
There's no need for this file

2021-10-01 21:58 UTC, Mu7ammadAbed commented on src/App.css
> +.App {
You are not using any of these styles o you should remove them

2021-10-01 21:58 UTC, Mu7ammadAbed commented on src/index.js
> +);
You need to add a new line here and I think you should import `BrowserRouter` and wrap your app with it here

2021-10-02 12:41 UTC, ahmadfarid-059 approved these changes

2021-10-02 12:47 UTC, ahmadfarid-059 submitted a review, later dismissed

2021-10-02 12:54 UTC, asmaaamin submitted a review, later dismissed

2021-10-02 14:19 UTC, ahmadfarid-059 approved these changes

2021-10-02 14:20 UTC, NadiaJalalTamimi approved these changes

2021-10-02 14:38 UTC, asmaaamin approved these changes

2021-10-03 08:57 UTC, Mu7ammadAbed approved these changes

2021-10-03 08:57 UTC, merged