database conniection and build
GSG-G10/divano pull request #25
Opened 2021-10-02 15:38 UTC by modrayyes

2021-10-02 16:28 UTC, ahmadfarid-059 submitted a review, later dismissed

2021-10-02 18:33 UTC, NadiaJalalTamimi approved these changes

2021-10-03 10:04 UTC, asmaaamin approved these changes

2021-10-03 10:54 UTC, ahmadfarid-059 submitted a review, later dismissed

2021-10-03 11:09 UTC, NadiaJalalTamimi approved these changes

2021-10-03 13:27 UTC, umarsalah requested changes

2021-10-03 13:27 UTC, umarsalah commented on server/database/connection/index.js
> +const connectionString = process.env.DB_URL;
You already define NODE_ENV in your package.json to use it here : 
```js
const {
  NODE_ENV,
  DB_DEV_URL,
  DATABASE_URL,
  TEST_DB_URL,
} = process.env;
```

Then initialize the switch case to know which DB to use 
```js
switch (NODE_ENV) {
  case 'production':
    dbUrl = DATABASE_URL;
    break;
  case 'development':
    dbUrl = DB_DEV_URL;
    break;
  case 'test':
    dbUrl = TEST_DB_URL;
    break;
  default:
    throw new Error('NO DATABASE to show!');
}
```

2021-10-03 13:27 UTC, umarsalah commented on server/database/connection/index.js
> +  connectionString,
and here we assign the ```dbUrl``` to ```connectionString```

2021-10-03 13:47 UTC, umarsalah commented on server/database/connection/index.js
> +const { DATABASE_URL, TEST_DB_URL, DEV_DB_URL } = process.env;
You can add ```NODE_ENV``` here instead of calling it many times with ``` process.env.NODE_ENV```

2021-10-03 13:56 UTC, ahmadfarid-059 approved these changes

2021-10-03 13:57 UTC, NadiaJalalTamimi approved these changes

2021-10-03 13:59 UTC, asmaaamin approved these changes

2021-10-03 14:05 UTC, umarsalah approved these changes

2021-10-03 14:06 UTC, merged