create sign up router
GSG-G10/divano pull request #45
Opened 2021-10-03 21:50 UTC by NadiaJalalTamimi

Relates #27

2021-10-03 21:52 UTC, ahmadfarid-059 approved these changes

2021-10-04 08:35 UTC, modrayyes submitted a review, later dismissed

2021-10-04 10:17 UTC, LinaYahya requested changes

2021-10-04 10:17 UTC, LinaYahya commented on server/app.js
> +app.use(express.static(join(__dirname, '..', 'client', 'public')));
we are going to run our client-side into different ways, In production, our files will be in `build` folder, and in the development, we don't need to send those files as we will run `npm start`, 
So we need to serve static files conditionally based on the environment we run

2021-10-04 10:17 UTC, LinaYahya commented on server/controllers/auth/signup.js
> +  const { username, password, email } = req.body;
what if user tries to signup with an existing email!?
Try to think about it

2021-10-04 10:17 UTC, LinaYahya commented on server/controllers/auth/signup.js
> +  hash(password, 10, (err, hashedPassword) => {
`hash` support promise, So use promise instead of callbacks.

2021-10-04 10:17 UTC, LinaYahya commented on server/controllers/auth/signup.js
> +          sign(
convert sign here to promise manually as `jsonwebtoken` doesn't support promises, export it from utils and use it here

2021-10-04 10:17 UTC, LinaYahya commented on server/controllers/auth/signup.js
> +                res.cookie('token', token, { httpOnly: true, secure: true });
while our token contains userID and userName, omit line 38 no need for that

2021-10-04 10:17 UTC, LinaYahya commented on server/controllers/auth/signup.js
> +                res.clearCookies('token', 'userInfo');
no need to clearCookies here, Also check the way clearCookies work

2021-10-04 10:17 UTC, LinaYahya commented on server/middlewares/signupValidation.js
> +  const { error } = signUpSchema.validate({
validate your body async would be better

2021-10-04 10:17 UTC, LinaYahya commented on server/middlewares/signupValidation.js
> +    res.status(422).json({
What is status 422 ??

2021-10-05 09:35 UTC, modrayyes approved these changes

2021-10-05 10:21 UTC, LinaYahya approved these changes

2021-10-05 10:31 UTC, modrayyes approved these changes

2021-10-05 10:47 UTC, ahmadfarid-059 approved these changes

2021-10-05 10:47 UTC, merged