cart router
GSG-G10/divano pull request #47
Opened 2021-10-03 23:05 UTC by NadiaJalalTamimi

Relates #46

2021-10-04 07:32 UTC, modrayyes approved these changes

2021-10-04 07:33 UTC, modrayyes approved these changes

2021-10-04 07:56 UTC, asmaaamin approved these changes

2021-10-04 12:17 UTC, LinaYahya requested changes

2021-10-04 12:17 UTC, LinaYahya commented on server/routes/index.js
> +router.get('/cart' , )
👀

2021-10-04 12:17 UTC, LinaYahya commented on server/controllers/pages/cart.js
> +  const { userId } = req.cookies;
You need to get userID from request cookies which are JWT, 
So first of all you need to verify your token.
As you need to check user identity in multiple routes, try to think about creating middleware that can handle this for you.

2021-10-04 12:17 UTC, LinaYahya commented on server/controllers/pages/cart.js
> +        res.status(500).json({ message: 'Internal server error' });
remove console, and you can just `next(err)` which will direct you to the **500** error controller

2021-10-05 10:16 UTC, modrayyes approved these changes

2021-10-05 10:24 UTC, LinaYahya approved these changes

2021-10-05 10:46 UTC, ahmadfarid-059 approved these changes

2021-10-05 10:49 UTC, merged